# Generated by Django 5.0.4 on 2024-04-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acounts',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
