# Generated by Django 5.0.4 on 2024-04-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_acounts_user_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
